# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SalesMobi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SalesMobi

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseInstanceID', '3.7.0'
  
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'RNReactNativeDocViewer', :path => '../node_modules/react-native-doc-viewer'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  target 'SalesMobiTests' do
    inherit! :search_paths
    
    # Pods for testing
  end



end
